import React from "react";
import Head from "next/head";
import styles from "./Layout.module.css";
import Navbar from "../Navbar/Navbar";

type LayoutProps = {
  children: React.ReactNode;
};

const Layout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Login Generic App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Zen+Dots&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Navbar />

      <main className={styles.main}>{children}</main>

      {/* <footer>
        <h1>THIS IS THE FOOTER</h1>
      </footer> */}
    </>
  );
};

export default Layout;
